# Generated by Django 4.2.30 on 2026-07-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='target',
            field=models.CharField(choices=[('hotel', '숙소'), ('flight', '항공')], default='hotel', max_length=12),
        ),
    ]
