# Generated by Django 4.2.30 on 2026-07-15 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
                ('price_krw', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('qty', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='provider.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.CharField(db_index=True, max_length=20, unique=True)),
                ('traveler_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('confirmed', '확정'), ('canceled', '취소')], default='confirmed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hold', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='provider.activityhold')),
            ],
        ),
    ]
