# Generated by Django 4.2.30 on 2026-07-10 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_itineraryday_itineraryitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='offer_id',
        ),
    ]
