# Generated by Django 4.2.30 on 2026-07-14 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_flight_expires_at_remove_flight_offer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', '확정'), ('failed', '실패')], max_length=12)),
                ('booking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.plan')),
            ],
        ),
    ]
