# Generated by Django 4.2.30 on 2026-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kind',
            field=models.CharField(choices=[('hotel', '숙소'), ('flight', '항공')], default='hotel', max_length=12),
        ),
    ]
