# Generated by Django 4.2.30 on 2026-07-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_booking_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='edit_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
