# Generated by Django 4.2.30 on 2026-07-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_plan_edit_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='title',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
