# Generated by Django 4.2.30 on 2026-07-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_triprequest_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='candidates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
